cmd_drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o := arm-linux-gnueabihf-gcc -Wp,-MD,drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/include -I/home/darrell/android/rockchip/rk3188/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-rk3188/include -Iarch/arm/plat-rk/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -I/home/darrell/android/rockchip/rk3188/drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/include -I/home/darrell/android/rockchip/rk3188/drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/ate/include -DANDROID_SUPPORT -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=7601U -DRESOURCE_PRE_ALLOC -DCE_BBP_NOISE_ENDURANCE_SUPPORT -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DADHOC_WPA2PSK_SUPPORT -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DRALINK_ATE -DCONFIG_RT2880_ATE_CMD_NEW -DRALINK_QA -DDYNAMIC_PD_SUPPORT -DCONFIG_P2P_AUTO_GO_AS_SOFTAP -DDOT11_N_SUPPORT -DP2P_SUPPORT -DAPCLI_SUPPORT -DMAT_SUPPORT -DAP_SCAN_SUPPORT -DSCAN_SUPPORT -DP2P_APCLI_SUPPORT -DCONFIG_AP_SUPPORT -DCONFIG_APSTA_MIXED_SUPPORT -DUAPSD_SUPPORT -DMBSS_SUPPORT -DIAPP_SUPPORT -DDOT1X_SUPPORT -DWSC_AP_SUPPORT -DWSC_STA_SUPPORT -DSTATS_COUNT_SUPPORT -DRT_CFG80211_SUPPORT -DEXT_BUILD_CHANNEL_LIST -DLED_CONTROL_SUPPORT -DCONFIG_PRE_ALLOC -DMT7601U -DMT7601 -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DRX_DMA_SCATTER -DVCORECAL_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DRTMP_INTERNAL_TX_ALC -DCONFIG_ANDES_SUPPORT -DCONFIG_RX_CSO_SUPPORT -DRTMP_FREQ_CALIBRATION_SUPPORT    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7601sta)" -c -o drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.c

source_drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o := drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.c

deps_drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \
    $(wildcard include/config/ap/support.h) \

drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o: $(deps_drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o)

$(deps_drivers/net/wireless/rkusbwifi/mt7601/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP/rate_ctrl/alg_ags.o):
