cmd_drivers/net/wireless/rtl8723bs/platform/platform_ops.o := arm-linux-gnueabihf-gcc -Wp,-MD,drivers/net/wireless/rtl8723bs/platform/.platform_ops.o.d  -nostdinc -isystem /usr/lib/gcc-cross/arm-linux-gnueabihf/4.8/include -I/home/darrell/android/rockchip/rk3188/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-rk3188/include -Iarch/arm/plat-rk/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -O1 -Wno-unused-variable -Wno-unused-value -Wno-unused-label -Wno-unused-parameter -Wno-unused-function -Wno-unused -Idrivers/net/wireless/rtl8723bs/include -Idrivers/net/wireless/rtl8723bs/platform -Idrivers/net/wireless/rtl8723bs/hal/OUTSRC-BTCoexist -DCONFIG_RTL8723B -DCONFIG_MP_INCLUDED -DCONFIG_POWER_SAVING -DCONFIG_BT_COEXIST -DCONFIG_TRAFFIC_PROTECT -DCONFIG_LOAD_PHY_PARA_FROM_FILE -DCONFIG_LITTLE_ENDIAN -DCONFIG_PLATFORM_ANDROID -DCONFIG_PLATFORM_ROCKCHIPS -DCONFIG_MINIMAL_MEMORY_USAGE -DRTW_ENABLE_WIFI_CONTROL_FUNC -DRTW_SUPPORT_PLATFORM_SHUTDOWN -DRTW_USE_CFG80211_STA_EVENT    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(platform_ops)"  -D"KBUILD_MODNAME=KBUILD_STR(8723bs)" -c -o drivers/net/wireless/rtl8723bs/platform/platform_ops.o drivers/net/wireless/rtl8723bs/platform/platform_ops.c

source_drivers/net/wireless/rtl8723bs/platform/platform_ops.o := drivers/net/wireless/rtl8723bs/platform/platform_ops.c

deps_drivers/net/wireless/rtl8723bs/platform/platform_ops.o := \
    $(wildcard include/config/platform/ops.h) \

drivers/net/wireless/rtl8723bs/platform/platform_ops.o: $(deps_drivers/net/wireless/rtl8723bs/platform/platform_ops.o)

$(deps_drivers/net/wireless/rtl8723bs/platform/platform_ops.o):
